### ISSUE TITLE
In the 'Try It Out' feature of the 'Definition' Tab the requestUrl is wrong

### ISSUE THREAD

**Issue by ydg** [microcks/microcks-backstage-provider#6]
### Describe the bug

I added a open-api spec to my microcks instance that I am running locally. On the microcks side the url for one of the mocked routes is http://localhost:8080/rest/Petstore+API/1.0.0/my/pets
![image](https://github.com/microcks/microcks-backstage-provider/assets/1163185/f05a4f06-bc92-4e3b-96e7-1cc860bc5e70)

Using the microcks-backstage-provider I am able to register this API, but when I want to use the 'Try It Out' feature for the mocked route the requestUrl populated is wrong http://localhost:3000/my/pets
![image](https://github.com/microcks/microcks-backstage-provider/assets/1163185/529b8a3a-361e-4b8c-90ed-ae9eb02c57a8)

### Expected behavior

The 'Try It Out' url should match the mock URL (not sure what to do in case of multiple mocks?)

### Actual behavior

The 'Try It Out' url does not match the mock URL

### Microcks version or git rev

0.0.2

### Install method (`docker-compose`, `helm chart`, `operator`, `docker-desktop extension`,...)

yarn

**Comment by lbroudoux** [comment]
Hello!

Thanks for your patience: the issue was created during vacations and I almost forget about it...
This is not actually a bug as it was never meant to work this way; however this is a nice feature enhancement 😉 

I had a look et Backstage API `OpenApiDefinition` component (see [here](https://github.com/backstage/backstage/blob/master/plugins/api-docs/src/components/OpenApiDefinitionWidget/OpenApiDefinition.tsx)) and unfortunately it's not made to be configurable through additional `Try It Out` URL. So it appears that the only way to do it is actually to add a `server` within the `servers` section of the API OpenAPI content so that Swagger UI would propose pointing to the Microcks mock definitions.

I think of enabling this behavior via an additional configuration flag like 'addOpenAPIServerUrl: true' (default would be false to let the OpenAPI unchanged). What do you think?
